"""create tables

Revision ID: 48330e411672
Revises: 
Create Date: 2025-06-17 18:44:43.576245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48330e411672'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_administrador',
    sa.Column('idadministrador', sa.Integer(), nullable=False),
    sa.Column('nomeadministrador', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idadministrador'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_tab_administrador_idadministrador'), 'tab_administrador', ['idadministrador'], unique=False)
    op.create_table('tab_avaliacao',
    sa.Column('idavaliacao', sa.Integer(), nullable=False),
    sa.Column('nomeavaliacao', sa.String(length=100), nullable=False),
    sa.Column('comentarioavaliacao', sa.Text(), nullable=False),
    sa.Column('respostaavaliacao', sa.Text(), nullable=True),
    sa.Column('dataavaliacao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('idavaliacao')
    )
    op.create_index(op.f('ix_tab_avaliacao_idavaliacao'), 'tab_avaliacao', ['idavaliacao'], unique=False)
    op.create_table('tab_ponto_turistico',
    sa.Column('idpontoturistico', sa.Integer(), nullable=False),
    sa.Column('nomepontoturistico', sa.String(length=100), nullable=False),
    sa.Column('descricaopontoturistico', sa.Text(), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('idpontoturistico')
    )
    op.create_index(op.f('ix_tab_ponto_turistico_idpontoturistico'), 'tab_ponto_turistico', ['idpontoturistico'], unique=False)
    op.create_table('tab_quartos',
    sa.Column('IdQuarto', sa.Integer(), nullable=False),
    sa.Column('NomeQuarto', sa.String(length=50), nullable=False),
    sa.Column('descricaoQuarto', sa.String(length=250), nullable=False),
    sa.Column('CapacidadeQuarto', sa.Integer(), nullable=False),
    sa.Column('ValorQuarto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagemQuartos', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('IdQuarto')
    )
    op.create_index(op.f('ix_tab_quartos_IdQuarto'), 'tab_quartos', ['IdQuarto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_quartos_IdQuarto'), table_name='tab_quartos')
    op.drop_table('tab_quartos')
    op.drop_index(op.f('ix_tab_ponto_turistico_idpontoturistico'), table_name='tab_ponto_turistico')
    op.drop_table('tab_ponto_turistico')
    op.drop_index(op.f('ix_tab_avaliacao_idavaliacao'), table_name='tab_avaliacao')
    op.drop_table('tab_avaliacao')
    op.drop_index(op.f('ix_tab_administrador_idadministrador'), table_name='tab_administrador')
    op.drop_table('tab_administrador')
    # ### end Alembic commands ###
