"""init

Revision ID: 5edbe8535c47
Revises: 
Create Date: 2025-05-10 19:14:55.384025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5edbe8535c47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tab_ponto_turistico',
    sa.Column('idpontoturistico', sa.Integer(), nullable=False),
    sa.Column('nomepontoturistico', sa.String(length=100), nullable=False),
    sa.Column('descricaopontoturistico', sa.String(length=250), nullable=False),
    sa.Column('linkpontoturistico', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('idpontoturistico')
    )
    op.create_index(op.f('ix_tab_ponto_turistico_idpontoturistico'), 'tab_ponto_turistico', ['idpontoturistico'], unique=False)
    op.create_table('tab_quartos',
    sa.Column('idquarto', sa.Integer(), nullable=False),
    sa.Column('capacidadequarto', sa.Integer(), nullable=False),
    sa.Column('valorquarto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cnpjpousada', sa.BigInteger(), nullable=False),
    sa.Column('nomequarto', sa.String(length=50), nullable=False),
    sa.Column('descricaoquarto', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('idquarto')
    )
    op.create_index(op.f('ix_tab_quartos_idquarto'), 'tab_quartos', ['idquarto'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tab_quartos_idquarto'), table_name='tab_quartos')
    op.drop_table('tab_quartos')
    op.drop_index(op.f('ix_tab_ponto_turistico_idpontoturistico'), table_name='tab_ponto_turistico')
    op.drop_table('tab_ponto_turistico')
    # ### end Alembic commands ###
